config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :meals

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  validates :main, :side, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  #get /meals
  def index
    @meals = Meal.all
  end

  #get /meals/show
  def show
    @meal = Meal.find(params[:id])
  end

  #get /meals/new
  def new
    @meal = Meal.new
  end

  #post /meals/create
  def create
    meal = Meal.create(meal_params)
    redirect_to meal_path(meal)
  end

  #get /meals/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  #put /meals/update
  def update
    meal = Meal.find(params[:id])
    meal.update(meal_params)

      if meal.save!
        redirect_to meal_path(meal)
      end
  end

  #delete /meals/destroy
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to meal_path
  end

  private 

  def meal_params
    params.require(:meal).permit(:main, :side)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meals/index.html.erb
<h1>Meal Ideas</h1>

<% @meals.each do |meal| %>
  <%= link_to meal.main, meal_path(meal) %> <br>
<% end %>

<br>
<br>

<%= link_to "Plan New Meals", new_meal_path %>

<br>

app/views/meals/new.html.erb
<h1>Plan a new Meal</h1>

<%= simple_form_for @meal do |form| %>
  <%= form.input :main %>
<br>
  <%= form.input :side %>
<br>
  <%= form.submit "Submit" %>
<%end %>

<br>

<%= link_to "Home Page", meals_path %>

app/views/meals/show.html.erb
<ul>
  <li>main: <%= @meal.main %></li>
  <li>side: <%= @meal.side %></li>
</ul>
<%= link_to "Edit", edit_meal_path(@meal) %>

<br>
<br>

<%= link_to "Home Page", meals_path %>

<br>